add composer

diff --git a/scripts/install b/scripts/install
--- a/scripts/install
+++ b/scripts/install
@@ -120,6 +120,27 @@ ynh_replace_string "yunopass"   "$db_pwd"     "$final_path/.env"
 ynh_replace_string "yunobase"   "$db_name"    "$final_path/.env"
 
 #=================================================
+# INSTALL COMPOSER
+#=================================================
+
+ynh_print_info "Install composer"
+
+EXPECTED_SIGNATURE=$(wget https://composer.github.io/installer.sig -O - -q)
+curl -s https://getcomposer.org/installer > composer-setup.php
+ACTUAL_SIGNATURE=$(php -r "echo hash_file('SHA384', 'composer-setup.php');")
+
+if [ "$EXPECTED_SIGNATURE" = "$ACTUAL_SIGNATURE" ]
+then
+    php composer-setup.php --quiet
+    RESULT=$?
+    rm composer-setup.php
+else
+    >&2 echo 'ERROR: Invalid composer installer signature'
+    rm composer-setup.php
+    exit 1
+fi
+
+#=================================================
 # NGINX CONFIGURATION
 #=================================================
 
